diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
core.editor="C:\\Program Files\\Notepad++\\notepad++.exe" -multiInst -notabbar -nosession -noPlugin
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
filesystem.Oracle Corporation|1.8.0_111|-1093236804.timestampresolution=16001 microseconds
filesystem.Oracle Corporation|1.8.0_111|-1093236804.minracythreshold=0 nanoseconds
user.name=Jair Ferraz
user.email=jairbferraz@outlook.com
filesystem.Oracle Corporation|11.0.9|-1093236804.timestampresolution=9994 microseconds
filesystem.Oracle Corporation|11.0.9|-1093236804.minracythreshold=0 nanoseconds
filesystem.Oracle Corporation|11.0.9|-1026027047.timestampresolution=13336 microseconds
filesystem.Oracle Corporation|11.0.9|-1026027047.minracythreshold=0 nanoseconds
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/jbferraz/STech-INF4M211-Pessoa.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
